apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      name: app
  template:
    metadata:
      labels:
        name: app
    spec:
      containers:
      - name: app
        image: us.gcr.io/geha-348521/python-appliction:v1
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: configMap